# -*- coding: utf-8 -*-
"""GroceryBilling.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HyQDomXz4UnSGIrCUVDRfnGGwTOzNP26
"""

#GROCERY STORE BILLING SYSTEM


#Accepting price inputs for 3 items
item1=float(input("Enter the price of item1: "))
item2=float(input("Enter the price of item2: "))
item3=float(input("Enter the price of item3: "))
discount=0

# Calculate original total cost
totalcost=item1+item2+item3

# Apply 10% discount if total > 50
if totalcost>50:
  discount=totalcost*0.10

# Calculate final amount after discount
finalamount=totalcost-discount

# Result
print("\nOriginal Total: $", format(totalcost, ".2f"))
print("Discount Total: $", format(discount, ".2f"))
print("Final Amount: $", format(finalamount, ".2f"))